name: oyun_gaming_flutter
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Base
  cupertino_icons: ^1.0.5
  nb_utils: ^4.6.20
  google_fonts: ^3.0.1
  cached_network_image: ^3.2.1
  step_progress_indicator: 1.0.2
  url_launcher: ^6.1.5

  # Firebase
  firebase_crashlytics: ^2.8.9
  firebase_core: ^1.21.1

  # STATE MANAGEMENT
  mobx: ^2.0.7+5
  flutter_mobx: ^2.0.6+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter:

  uses-material-design: true

  assets:
    - images/oyunGaming/
    - images/flag/

